---
access1:
  hostname: 10.0.0.2
  groups:
    - access
telnet1:
  hostname: 172.16.253.1
  platform: cisco_ios_telnet
  connection_options:
    netmiko:
      port: 5002
  extras:
    fast_cli: False
    global_delay_factor: 2
  groups:
   - telnet